server {
    listen 80;
    server_name localhost;

    # ドキュメントルートを drrr-like-chat 直下に指定
    root /var/www/html/drrr-like-chat;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHPファイルの実行設定
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # セキュリティ設定
    location ~ /trust_path/ {
        deny all;
        return 404;
    }
}